//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Area
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Area()
        {
            this.Tables = new HashSet<Table>();
            this.Registers = new HashSet<Register>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _restaurantid;
        public  System.Guid RestaurantId 
		{ 
			get
			{ 
				return _restaurantid; 
			} 
			set
			{
				_restaurantid = value;
				ObjectPropertyChanged("RestaurantId");
			}
		}
    	private int _stateid;
        public  int StateId 
		{ 
			get
			{ 
				return _stateid; 
			} 
			set
			{
				_stateid = value;
				ObjectPropertyChanged("StateId");
			}
		}
    	private string _description;
        public  string Description 
		{ 
			get
			{ 
				return _description; 
			} 
			set
			{
				_description = value;
				ObjectPropertyChanged("Description");
			}
		}
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<Table> Tables { get; set; }
        public virtual ICollection<Register> Registers { get; set; }
    }
}
