//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class MenuProduct
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public MenuProduct()
        {
            this.SaleLineItems = new HashSet<SaleLineItem>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _menuid;
        public  System.Guid MenuId 
		{ 
			get
			{ 
				return _menuid; 
			} 
			set
			{
				_menuid = value;
				ObjectPropertyChanged("MenuId");
			}
		}
    	private System.Guid _productid;
        public  System.Guid ProductId 
		{ 
			get
			{ 
				return _productid; 
			} 
			set
			{
				_productid = value;
				ObjectPropertyChanged("ProductId");
			}
		}
    	private decimal _price;
        public  decimal Price 
		{ 
			get
			{ 
				return _price; 
			} 
			set
			{
				_price = value;
				ObjectPropertyChanged("Price");
			}
		}
    
        public virtual Product Product { get; set; }
        public virtual ICollection<SaleLineItem> SaleLineItems { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
