//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal abstract partial class Payment
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _saleid;
        public  System.Guid SaleId 
		{ 
			get
			{ 
				return _saleid; 
			} 
			set
			{
				_saleid = value;
				ObjectPropertyChanged("SaleId");
			}
		}
    	private decimal _amount;
        public  decimal Amount 
		{ 
			get
			{ 
				return _amount; 
			} 
			set
			{
				_amount = value;
				ObjectPropertyChanged("Amount");
			}
		}
    
        public virtual Sale Sale { get; set; }
    }
}
