//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Product
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Product()
        {
            this.MenuProducts = new HashSet<MenuProduct>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _categoryid;
        public  System.Guid CategoryId 
		{ 
			get
			{ 
				return _categoryid; 
			} 
			set
			{
				_categoryid = value;
				ObjectPropertyChanged("CategoryId");
			}
		}
    	private decimal _price;
        public  decimal Price 
		{ 
			get
			{ 
				return _price; 
			} 
			set
			{
				_price = value;
				ObjectPropertyChanged("Price");
			}
		}
    	private string _description;
        public  string Description 
		{ 
			get
			{ 
				return _description; 
			} 
			set
			{
				_description = value;
				ObjectPropertyChanged("Description");
			}
		}
    
        public virtual Category Category { get; set; }
        public virtual ICollection<MenuProduct> MenuProducts { get; set; }
    }
}
