//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Register
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Register()
        {
            this.Sales = new HashSet<Sale>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private System.Guid _areaid;
        public  System.Guid AreaId 
		{ 
			get
			{ 
				return _areaid; 
			} 
			set
			{
				_areaid = value;
				ObjectPropertyChanged("AreaId");
			}
		}
    	private string _name;
        public  string Name 
		{ 
			get
			{ 
				return _name; 
			} 
			set
			{
				_name = value;
				ObjectPropertyChanged("Name");
			}
		}
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
