//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Restaurant
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Restaurant()
        {
            this.Areas = new HashSet<Area>();
            this.People = new HashSet<Person>();
            this.Menus = new HashSet<Menu>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private string _name;
        public  string Name 
		{ 
			get
			{ 
				return _name; 
			} 
			set
			{
				_name = value;
				ObjectPropertyChanged("Name");
			}
		}
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
    }
}
