//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class TableSale : Sale
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
    	private System.Guid _tableid;
        public  System.Guid TableId 
		{ 
			get
			{ 
				return _tableid; 
			} 
			set
			{
				_tableid = value;
				ObjectPropertyChanged("TableId");
			}
		}
    
        public virtual Table Table { get; set; }
    }
}
